# Generated by Django 4.0.3 on 2022-03-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('trade_code', models.CharField(max_length=10000)),
                ('high', models.CharField(max_length=10000)),
                ('low', models.CharField(max_length=10000)),
                ('open', models.CharField(max_length=10000)),
                ('close', models.CharField(max_length=10000)),
                ('volume', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'web_member',
            },
        ),
    ]
