# Generated by Django 4.0.3 on 2022-03-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='visualdata',
            table=None,
        ),
    ]
