# Generated by Django 4.0.3 on 2022-03-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0004_alter_visualdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualdata',
            name='volume',
            field=models.IntegerField(),
        ),
    ]
