# Generated by Django 4.0.3 on 2022-03-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0005_alter_visualdata_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualdata',
            name='close',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='visualdata',
            name='high',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='visualdata',
            name='low',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='visualdata',
            name='open',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='visualdata',
            name='volume',
            field=models.CharField(max_length=10000),
        ),
    ]
